from turtle import *
import math
window=Screen()
window.bgcolor("teal")
turtle1=Turtle()
turtle1.speed(100)
turtle1.penup()
turtle1.setpos(00,-100)
turtle1.pendown()
turtle1.circle(100)
turtle1.up()
turtle1.setpos(0,100)
for i in range(360):
    ang=turtle1.heading()
    turtle1.setheading(270)
    turtle1.forward(10)
    turtle1.pendown()
    turtle1.circle(10)
    turtle1.setheading(90)
    turtle1.penup()
    turtle1.forward(10)
    turtle1.setheading(ang+1)
    turtle1.right(1)
    turtle1.forward(1)
window.mainloop()
